# Generated by Django 4.1.1 on 2022-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_kelompok_dosen_kelompok_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
