# Generated by Django 4.1.1 on 2022-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0004_alter_dosen_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.ImageField(upload_to='C:/projecttik/untirta/dosen/static/dosen/images'),
        ),
    ]
