# Generated by Django 4.1.1 on 2022-09-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faperta',
        ),
    ]
