# Generated by Django 4.1.1 on 2022-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faperta', '0002_delete_faperta'),
    ]

    operations = [
        migrations.CreateModel(
            name='faperta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=20)),
                ('Nama', models.CharField(max_length=100)),
                ('Tanggal_Lahir', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Fakultas', models.CharField(max_length=100)),
                ('Prodi', models.CharField(max_length=150)),
                ('Alamat', models.CharField(max_length=250)),
            ],
        ),
    ]
