# Generated by Django 4.1.1 on 2022-10-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0004_dosen_delete_faperta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dosen',
        ),
    ]
