# Generated by Django 4.1.1 on 2022-10-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('ttl', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='C:/projecttik/untirta/dosen/static/dosen/images')),
                ('email', models.CharField(max_length=200)),
                ('fakultas', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=150)),
                ('kelompok_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.kelompok')),
            ],
        ),
    ]
